// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "order/pkg/pb"
)

// InventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type InventoryServiceClient struct {
	mock.Mock
}

// DecreaseItemQuantity provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) DecreaseItemQuantity(ctx context.Context, in *pb.DecreaseItemQuantityRequest, opts ...grpc.CallOption) (*pb.DecreaseItemQuantityResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.DecreaseItemQuantityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DecreaseItemQuantityRequest, ...grpc.CallOption) (*pb.DecreaseItemQuantityResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DecreaseItemQuantityRequest, ...grpc.CallOption) *pb.DecreaseItemQuantityResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.DecreaseItemQuantityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.DecreaseItemQuantityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItem provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) GetItem(ctx context.Context, in *pb.GetItemRequest, opts ...grpc.CallOption) (*pb.GetItemResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.GetItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetItemRequest, ...grpc.CallOption) (*pb.GetItemResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetItemRequest, ...grpc.CallOption) *pb.GetItemResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInventoryServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewInventoryServiceClient creates a new instance of InventoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInventoryServiceClient(t mockConstructorTestingTNewInventoryServiceClient) *InventoryServiceClient {
	mock := &InventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
